// This file is auto-generated by @hey-api/openapi-ts

export { getPing, type Options } from './sdk.gen';
export type { ClientOptions, GetPingData, GetPingResponse, GetPingResponses } from './types.gen';
