// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'https://silfak-api.vercel.app/api' | (string & {});
};

export type RegisterInput = {
    email: string;
    name: string;
    nim: string;
    password: string;
    passwordConfirmation: string;
};

export type LoginInput = {
    email: string;
    password: string;
};

export type ChangePasswordInput = {
    oldPassword: string;
    newPassword: string;
    passwordConfirmation: string;
};

export type UserInput = {
    name: string;
    email: string;
    password: string;
};

export type UserUpdateInput = {
    name?: string;
    email?: string;
};

export type UserListItem = {
    id: string;
    name: string;
    email: string;
    isActive: boolean;
    role: {
        name: string;
    };
};

export type CreateBuildingInput = {
    name: string;
};

export type UpdateBuildingInput = {
    name?: string;
};

export type Building = {
    id: string;
    name: string;
    createdAt: string | null;
};

export type CreateRoomInput = {
    name: string;
    buildingId: string;
    floor: number;
};

export type UpdateRoomInput = {
    name?: string;
    buildingId?: string;
    floor?: number;
};

export type Room = {
    id: string;
    name: string;
    buildingId: string;
    createdAt: string | null;
    floor: number;
};

export type CreateReportInput = {
    reporterId: string;
    roomId: string;
    description: string;
    imageUrl?: string;
    status?: 'REPORTED' | 'IN_PROGRESS' | 'RESOLVED';
    isUrgent?: boolean;
    categoryId: string;
};

export type UpdateReportInput = {
    reporterId?: string;
    roomId?: string;
    description?: string;
    imageUrl?: string;
    status?: 'REPORTED' | 'IN_PROGRESS' | 'RESOLVED';
    isUrgent?: boolean;
    categoryId?: string;
};

export type Report = {
    id: string;
    reporterId: string;
    roomId: string;
    description: string | null;
    imageUrl: string | null;
    status: string | null;
    isUrgent: boolean;
    categoryId: string;
};

export type ErrorResponse = {
    success: false;
    message: string;
};

export type ValidationErrorResponse = {
    success: false;
    message: string;
    errors: Array<{
        field: string;
        message: string;
    }>;
};

export type PostAuthRegisterData = {
    body?: RegisterInput;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type PostAuthRegisterErrors = {
    /**
     * Conflict — user or NIM already exists
     */
    409: unknown;
    /**
     * Validation failed
     */
    422: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type PostAuthRegisterResponses = {
    /**
     * User registered successfully
     */
    201: unknown;
};

export type PostAuthLoginData = {
    body?: LoginInput;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type PostAuthLoginErrors = {
    /**
     * Invalid credentials
     */
    401: unknown;
    /**
     * Validation failed
     */
    422: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type PostAuthLoginResponses = {
    /**
     * Login successful
     */
    200: {
        success?: boolean;
        message?: string;
        data?: {
            token: string;
            user: UserListItem;
        };
    };
};

export type PostAuthLoginResponse = PostAuthLoginResponses[keyof PostAuthLoginResponses];

export type PutAuthChangePasswordData = {
    body?: ChangePasswordInput;
    path?: never;
    query?: never;
    url: '/auth/change-password';
};

export type PutAuthChangePasswordErrors = {
    /**
     * Bad request — passwords do not match
     */
    400: unknown;
    /**
     * Unauthenticated — token missing or invalid
     */
    401: unknown;
    /**
     * Validation failed
     */
    422: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type PutAuthChangePasswordResponses = {
    /**
     * Password changed successfully
     */
    200: unknown;
};

export type GetUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users';
};

export type GetUsersErrors = {
    /**
     * Unauthenticated
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type GetUsersResponses = {
    /**
     * Users fetched successfully
     */
    200: {
        success?: boolean;
        message?: string;
        data?: Array<UserListItem>;
    };
};

export type GetUsersResponse = GetUsersResponses[keyof GetUsersResponses];

export type PostUsersObData = {
    body?: UserInput;
    path?: never;
    query?: never;
    url: '/users/OB';
};

export type PostUsersObErrors = {
    /**
     * Unauthenticated
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Role OB not found
     */
    404: unknown;
    /**
     * Conflict — user already exists
     */
    409: unknown;
    /**
     * Validation failed
     */
    422: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type PostUsersObResponses = {
    /**
     * OB user created successfully
     */
    201: unknown;
};

export type GetUsersByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type GetUsersByIdErrors = {
    /**
     * Unauthenticated
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * User not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type GetUsersByIdResponses = {
    /**
     * User fetched successfully
     */
    200: unknown;
};

export type PutUsersByIdData = {
    body?: UserUpdateInput;
    path: {
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type PutUsersByIdErrors = {
    /**
     * Unauthenticated
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * User not found
     */
    404: unknown;
    /**
     * Validation failed
     */
    422: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type PutUsersByIdResponses = {
    /**
     * User updated successfully
     */
    200: unknown;
};

export type PatchUsersByIdStatusData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/users/{id}/status';
};

export type PatchUsersByIdStatusErrors = {
    /**
     * Unauthenticated
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * User not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type PatchUsersByIdStatusResponses = {
    /**
     * User status updated successfully
     */
    200: unknown;
};

export type GetBuildingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/buildings';
};

export type GetBuildingsErrors = {
    /**
     * Unauthenticated
     */
    401: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type GetBuildingsResponses = {
    /**
     * Buildings fetched successfully
     */
    200: {
        success?: boolean;
        message?: string;
        data?: Array<Building>;
    };
};

export type GetBuildingsResponse = GetBuildingsResponses[keyof GetBuildingsResponses];

export type PostBuildingsData = {
    body?: CreateBuildingInput;
    path?: never;
    query?: never;
    url: '/buildings';
};

export type PostBuildingsErrors = {
    /**
     * Unauthenticated
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Validation failed
     */
    422: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type PostBuildingsResponses = {
    /**
     * Building created successfully
     */
    201: unknown;
};

export type DeleteBuildingsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/buildings/{id}';
};

export type DeleteBuildingsByIdErrors = {
    /**
     * Unauthenticated
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Building not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type DeleteBuildingsByIdResponses = {
    /**
     * Building deleted successfully
     */
    200: unknown;
};

export type GetBuildingsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/buildings/{id}';
};

export type GetBuildingsByIdErrors = {
    /**
     * Building not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type GetBuildingsByIdResponses = {
    /**
     * Building fetched successfully
     */
    200: unknown;
};

export type PutBuildingsByIdData = {
    body?: UpdateBuildingInput;
    path: {
        id: string;
    };
    query?: never;
    url: '/buildings/{id}';
};

export type PutBuildingsByIdErrors = {
    /**
     * Unauthenticated
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Building not found
     */
    404: unknown;
    /**
     * Validation failed
     */
    422: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type PutBuildingsByIdResponses = {
    /**
     * Building updated successfully
     */
    200: unknown;
};

export type GetRoomsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/rooms';
};

export type GetRoomsErrors = {
    /**
     * Unauthenticated
     */
    401: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type GetRoomsResponses = {
    /**
     * Rooms fetched successfully
     */
    200: {
        success?: boolean;
        message?: string;
        data?: Array<Room>;
    };
};

export type GetRoomsResponse = GetRoomsResponses[keyof GetRoomsResponses];

export type PostRoomsData = {
    body?: CreateRoomInput;
    path?: never;
    query?: never;
    url: '/rooms';
};

export type PostRoomsErrors = {
    /**
     * Unauthenticated
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Validation failed
     */
    422: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type PostRoomsResponses = {
    /**
     * Room created successfully
     */
    201: unknown;
};

export type DeleteRoomsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/rooms/{id}';
};

export type DeleteRoomsByIdErrors = {
    /**
     * Unauthenticated
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Room not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type DeleteRoomsByIdResponses = {
    /**
     * Room deleted successfully
     */
    200: unknown;
};

export type GetRoomsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/rooms/{id}';
};

export type GetRoomsByIdErrors = {
    /**
     * Room not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type GetRoomsByIdResponses = {
    /**
     * Room fetched successfully
     */
    200: unknown;
};

export type PutRoomsByIdData = {
    body?: UpdateRoomInput;
    path: {
        id: string;
    };
    query?: never;
    url: '/rooms/{id}';
};

export type PutRoomsByIdErrors = {
    /**
     * Unauthenticated
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Room not found
     */
    404: unknown;
    /**
     * Validation failed
     */
    422: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type PutRoomsByIdResponses = {
    /**
     * Room updated successfully
     */
    200: unknown;
};

export type GetReportsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/reports';
};

export type GetReportsErrors = {
    /**
     * Unauthenticated
     */
    401: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type GetReportsResponses = {
    /**
     * Reports fetched successfully
     */
    200: {
        success?: boolean;
        message?: string;
        data?: Array<Report>;
    };
};

export type GetReportsResponse = GetReportsResponses[keyof GetReportsResponses];

export type PostReportsData = {
    body?: CreateReportInput;
    path?: never;
    query?: never;
    url: '/reports';
};

export type PostReportsErrors = {
    /**
     * Unauthenticated
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Validation failed
     */
    422: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type PostReportsResponses = {
    /**
     * Report created successfully
     */
    201: unknown;
};

export type DeleteReportsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/reports/{id}';
};

export type DeleteReportsByIdErrors = {
    /**
     * Unauthenticated
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Report not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type DeleteReportsByIdResponses = {
    /**
     * Report deleted successfully
     */
    200: unknown;
};

export type GetReportsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/reports/{id}';
};

export type GetReportsByIdErrors = {
    /**
     * Report not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type GetReportsByIdResponses = {
    /**
     * Report fetched successfully
     */
    200: unknown;
};

export type PatchReportsByIdData = {
    body?: UpdateReportInput;
    path: {
        id: string;
    };
    query?: never;
    url: '/reports/{id}';
};

export type PatchReportsByIdErrors = {
    /**
     * Unauthenticated
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Report not found
     */
    404: unknown;
    /**
     * Validation failed
     */
    422: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type PatchReportsByIdResponses = {
    /**
     * Report updated successfully
     */
    200: unknown;
};
