// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://openapi.json` | (string & {});
};

export type GetPingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ping';
};

export type GetPingResponses = {
    /**
     * OK
     */
    200: {
        message?: string;
    };
};

export type GetPingResponse = GetPingResponses[keyof GetPingResponses];
